#' chooseArdNMF
#'
#' Select a optimal ARD-NMF run as final result to return for de novo signature definition assignment
#'
#' @param runs An object of class PLACEHOLDER-CLASS containing ARD-NMF runs (typically generated by [CINSignatureQuantification::calculateArdNMF()])
#' @param method Method to select the optimal number of decomposed signatures (k) (Default: "modal")
#' @param k Manually select the number of signatures (k) to return from list of ARD-NMF solutions (Default: NULL)
#' @param decision Optimisation metric to select best solution from selected subset of K signatures (Default: "bdiv")
#' @param specificRun A character string specifying a specific run to select from list of ARD-NMF solutions
#'
#' @return A list containing signature definitions and supporting ARD-NMF results for optimal solution
#' @export chooseArdNMF
#'
chooseArdNMF <- function(runs = NULL,method="modal",k=NULL,decision="bdiv",specificRun=NULL){
    if(is.null(runs)){
        stop("runs not specified")
    }
    if(!method %in% c("modal","agnostic")){
        stop("unknown selection method")
    }
    if(!decision %in% c("bdiv","obj")){
        stop("unknown decision method")
    }

    if(is.null(specificRun)){
        kvals <- unlist(sapply(runs,FUN = function(x){x$nsigs}))
        if(!is.null(k)){
            if(!k %in% kvals){
                stop("User-specified 'k' number of sigs not present in any run")
            } else {
                message(paste0("selecting user-specified k - ",k))
                nsig <- k
            }
        } else {
            if(method == "modal"){
                nsig <- collapse::fmode(kvals,ties="min")
                message(paste0("selecting modal k - ",nsig))
            } else {
                message("using k-agnostic")
                nsig <- NULL
            }
        }

        if(!is.null(nsig)){
            #print(kvals)
            #print(nsig)
            #print(kvals == nsig)
            subruns <- runs[kvals == nsig]
            message(paste0("runs matching k - ",paste0(names(subruns),collapse = ",")))
        } else {
            subruns <- runs
        }

        best_run <- select_optimal_k(subrun = subruns,decision = decision)

        finalsubruns <- subruns[[best_run]]
    } else {
        if(specificRun %in% names(runs)){
            message(paste0("User-specified run selected -",specificRun))
            finalsubruns <- runs[[specificRun]]
        } else {
            stop("specified run not found in list of runs")
        }
    }
    return(finalsubruns)
}

select_optimal_k <- function(subrun=NULL,decision="bdiv"){
    if(decision == "bdiv"){
        div <- sapply(subrun,FUN = function(x) x$report[nrow(x$report),"b_div"])
    } else if(decision == "obj"){
        div <- sapply(subrun,FUN = function(x) x$report[nrow(x$report),"obj"])
    } else {
        stop("unknown method")
    }
    min_div <- min(div)
    divmin <- which(div %in% min_div)
    best_run_name <- names(div)[divmin]
    message(paste0("best run - ",best_run_name))
    return(best_run_name)
}
