#' fitMixturePois
#'
#' Fit mixture model using flexmix to set of components with Poisson
#' distributions
#'
#' @param component two-dimensional data.frame containing sample names and values of computed copy number features generated by calculateFeatures()
#' @param seed Numeric or string as a input value for set.seed() function - Currently disabled (Default: '77777')
#' @param model_selection String to specify model selection method of available "AIC", "BIC", or "ICL" (default: "BIC")
#' @param min_prior FLXcontrol value - Minimum prior probability of clusters, components falling below this threshold are removed during the iteration (default: 0.001)
#' @param niter FLXcontrol value - Maximum number of iterations (default: 1000)
#' @param nrep Number of random initialisations to run per mixture component step (default: 1)
#' @param min_comp Minimum of mixture components to compute (default: 2)
#' @param max_comp Minimum of mixture components to compute (default: 10)
#' @returns data.table containing the mean and weights of fitted poisson mixture
#'   models
fitMixturePois <- function(component=NULL,seed=77777,model_selection="BIC",min_prior=0.001,niter=1000,nrep=1,min_comp=2,max_comp=10){
    if(!requireNamespace("flexmix", quietly = TRUE)){
        stop("package 'flexmix' is not installed and is required to fit mixture models")
    }
    if(is.null(component)){
        stop("component is null")
    }
    #set.seed(seed)
    # set the column names to fix bpchrarm naming
    colnames(component) <- c("ID","value")

    control <- generateControl(min_prior = min_prior, niter = niter)
    model <- fitPoisModel(component = component$value,min_comp = min_comp,max_comp = max_comp,
                          nrep = nrep, control = control,model_selection = model_selection)
    return(model)
}

generateControl <- function(min_prior,niter){
    control <- methods::new("FLXcontrol")
    control@minprior <- min_prior
    control@iter.max <- niter
    return(control)
}

fitPoisModel <- function(component,min_comp,max_comp,nrep,control,model_selection){
    fitPoismessage <- paste0("fitting poisson mixture models")
    message(fitPoismessage)
    fit <- flexmix::stepFlexmix(component ~ 1,verbose = T,
                                model = flexmix::FLXMCmvpois(),
                                k=min_comp:max_comp,nrep=nrep,control=control)
    fit <- flexmix::getModel(fit,which=model_selection)
    return(fit)
}

formatPoisModel <- function(model){
    componentMeans <- modeltools::parameters(model)
    ## get prior probability for component assignment
    ## equivalent to colSums(fitted@posterior$scaled) / sum(fitted@posterior$scaled)
    componentPriors <- modeltools::prior(model)
    CompTab <- data.table::data.table(Mean = componentMeans,Weight = componentPriors)
    CompTab <- CompTab[order(CompTab$Mean)]
    return(CompTab)
}
